services:
  discord_bot:
    build:
      context: ./
    environment:
      - LOG_LEVEL=DEBUG
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TARGET_GUILD=${TARGET_GUILD}
      - HYPIXEL_API_KEY=${HYPIXEL_API_KEY}
      - DB_URL=postgresql://postgres:pass@database:5432/postgres
    depends_on:
      - database
    user: "1000:2000"

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  # For debugging
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: { }
