services:
  discord_bot:
    build:
      context: ./
    environment:
      - LOG_LEVEL=DEBUG
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TARGET_GUILD=${TARGET_GUILD}
      - HYPIXEL_API_KEY=${HYPIXEL_API_KEY}
      - DB_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  # For debugging
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: { }
