[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
discord-py-interactions = "^5.14.0"
tortoise-orm = { extras = ["asyncpg"], version = "^0.24.0" }
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core==1.8.5"]
build-backend = "poetry.core.masonry.api"
